management:
    endpoints:
        web:
            exposure:
                include: "*"

eureka:
    instance:
        leaseRenewalIntervalInSeconds: 10
        health-check-url-path: /actuator/health
    client:
        registryFetchIntervalSeconds: 5
        serviceUrl:
            defaultZone: http://eureka-server:8761/eureka/

