version: "3.5"
services:
  rabbitmq:
    image: rabbitmq:management
    ports:
      - "5672:5672"
      - "15672:15672"

  configserver:
    image: tjonahen/configserver
    ports:
      - "8888:8888"
    volumes:
      - /home/ordina/NetBeansProjects/config:/config-repo

  eurekaserver:
    image: tjonahen/eurekaserver
    ports:
      - "8761:8761"
