version: "3.5"
services:
  rabbitmq:
    image: rabbitmq:management
    ports:
      - "5672:5672"
      - "15672:15672"
    restart: unless-stopped

  configserver:
    image: tjonahen/configserver
    environment:
      - PROGRAM_OPTS=-Dcom.sun.management.jmxremote -Dcom.sun.management.jmxremote.port=9090 -Dcom.sun.management.jmxremote.ssl=false -Dcom.sun.management.jmxremote.authenticate=false -Dcom.sun.management.jmxremote.local.only=false
      - LOGGING_FILE=/logs/application-config.log
    ports:
      - "8888:80"
      - "9999:9090"
    volumes:
      - /home/ordina/Projects/NetBeansProjects/config:/config-repo
      - vlogs:/logs
    restart: unless-stopped

  eurekaserver:
    image: tjonahen/eurekaserver
    environment:
      - PROGRAM_OPTS=-Dcom.sun.management.jmxremote -Dcom.sun.management.jmxremote.port=9090 -Dcom.sun.management.jmxremote.ssl=false -Dcom.sun.management.jmxremote.authenticate=false -Dcom.sun.management.jmxremote.local.only=false
      - LOGGING_FILE=/logs/application-eureka.log
    ports:
      - "8761:80"
      - "9761:9090"
    volumes:
      - vlogs:/logs
    restart: unless-stopped

  splunkforwarder:
    image: splunk/universalforwarder
    environment:
     - SPLUNK_START_ARGS=--accept-license
     - SPLUNK_PASSWORD=admin1234
    volumes:
     - vlogs:/logs
    restart: unless-stopped

volumes:
  vlogs:

networks:
  default:
    external:
      name: local-sb-network
